### ISSUE TITLE
Wrong status code when fail authentication.

### ISSUE THREAD

**Issue by alejosv** [makinhs/rest-api-tutorial#11]
According to the HTTP-based authentication protocol, the code to send when authentication has failed is `401` and not `404`, since the `/auth` resource does exist.

https://github.com/makinhs/rest-api-tutorial/blob/fcba18a4ee61d1231cbf5400a286126ee3ce22cb/authorization/middlewares/verify.user.middleware.js#L26-L29

**Comment by TylerByte666** [comment]
The 

> /auth 

is a **route/endpoint** and sure it exists. But that is not what the code above is doing.

It is telling you that the user resource does not exist, specifically the one you requested. 
So the original is 100% correct and should not be changed!
