### ISSUE TITLE
Wrong ADMIN_PERMISSION in Middleware: auth.permission.middleware.js

### ISSUE THREAD

**Issue by TylerByte666** [makinhs/rest-api-tutorial#20]
Hello and thank you for a wonderful tutorial!

I noticed the wrong admin permission value is used within `common\middlewares\auth.permission.middleware.js`, line 4:
```js
const ADMIN_PERMISSION = 4096;
```
### Fix #21:
I will create a **PR** shortly where I have changed that line to reflect the settings already set int the `common\config\env.config.js` and use this instead:
```js
const ADMIN_PERMISSION = require('../config/env.config')['permissionLevels']['ADMIN'];

if (user_permission_level & ADMIN_PERMISSION) {
   ...
}
```
That should be a super clean fix, and I hope it helps 😄

**Comment by makinhs** [comment]
Thanks for the contribution @TylerByte666 

Unfortunately I am not having time to keep following this project. I approved your PR and merged to our main branch
